In [30]:
import numpy as np

In [31]:
#Crear lista de números primos
numeros_primos = [2,3,5,7,11,13,17,19,23,29]
numeros_primos

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

In [32]:
# Crear array a partir de lista de
array_primos = np.array(numeros_primos)
array_primos

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [33]:
array_zeros=np.zeros(10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
array_numeros=np.arange(10)
array_numeros

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
array_pares=np.arange(0,20,2)
array_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
#Array de mas de una dimensione del
array_pares.reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [37]:
# Operaciones aritmeticas sobre np array 1-dimension y 2-dimension
array_impares=array_pares+1
array_impares


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [38]:
#multiplicar por 100
array_pares *100


array([   0,  200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800])

In [39]:
#resta entre array
array_impares - array_pares

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [40]:
#cuidado división por cero
array_impares / array_pares

C:\Users\carol\AppData\Local\Temp\ipykernel_22488\3981435483.py:2: RuntimeWarning: divide by zero encountered in true_divide
  array_impares / array_pares


array([       inf, 1.5       , 1.25      , 1.16666667, 1.125     ,
       1.1       , 1.08333333, 1.07142857, 1.0625    , 1.05555556])

In [41]:
#Métodos asociados a Estadistica
#Suma
array_primos.sum()

129

In [42]:
#Promedio
array_primos.mean()

12.9

In [43]:
#Varianza
array_primos.var()

73.28999999999999

In [44]:
#Como ordenar un np array
array_fibonacci = np.array([55,0,144,1,21,89,5,8,13,1,34,3,2])

In [45]:
# Orden ascendente: de menor a mayor
np.sort(array_fibonacci)

array([  0,   1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144])

In [46]:
# Orden descendente: de mayor a menor
-np.sort(-array_fibonacci)


array([144,  89,  55,  34,  21,  13,   8,   5,   3,   2,   1,   1,   0])

In [47]:
A = np.arange(0,20,2).reshape(2,5)
A

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [48]:
# Como seleccionar elementos

In [50]:
#Seleccionar el primero elemento
A[0,0]

0

In [51]:
#Seleccionar algún otro elemento
A[1,3]

16

In [53]:
#Seleccionar varios elementos

In [54]:
#Selecciomar por fila
A[1,:]

array([10, 12, 14, 16, 18])

In [55]:
#Seleccionar por columna
A[:,3]

array([ 6, 16])

In [56]:
#Utilizar filter
array_fibonacci

array([ 55,   0, 144,   1,  21,  89,   5,   8,  13,   1,  34,   3,   2])

In [57]:
#Condición para mejores de 20
array_fibonacci <20

array([False,  True, False,  True, False, False,  True,  True,  True,
        True, False,  True,  True])

In [58]:
#Filtrar menores de 20
array_fibonacci[array_fibonacci<20]

array([ 0,  1,  5,  8, 13,  1,  3,  2])