In [3]:
import numpy as np

In [4]:
#Crear lista de números primos
numeros_primos = [2,3,5,7,11,13,17,19,23,29]
numeros_primos

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

In [6]:
# Crear array a partir de lista de
array_primos = np.array(numeros_primos)
array_primos

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [7]:
array_zeros=np.zeros(10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
array_numeros=np.arange(10)
array_numeros

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
array_pares=np.arange(0,20,2)
array_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
#Array de mas de una dimensione del
array_pares.reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [15]:
# Operaciones aritmeticas sobre np array 1-dimension y 2-dimension
array_impares=array_pares+1
array_impares


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [18]:
#multiplicar por 100
array_pares *100


array([   0,  200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800])

In [19]:
#resta entre array
array_impares - array_pares

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
#cuidado división por cero
array_impares / array_pares

C:\Users\carol\AppData\Local\Temp\ipykernel_22488\3981435483.py:2: RuntimeWarning: divide by zero encountered in true_divide
  array_impares / array_pares


array([       inf, 1.5       , 1.25      , 1.16666667, 1.125     ,
       1.1       , 1.08333333, 1.07142857, 1.0625    , 1.05555556])